FROM bitnami/minideb:bullseye

# download packages that aren't included in minideb
RUN sudo apt-get update -y && \
    sudo apt-get install -y ncurses-bin \
    sudo apt-get install -y build-essential 
