# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish to KevSite

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Clean up the workspace
        run: sudo rm -rf $GITHUB_WORKSPACE

      - name: Check out the repo
        uses: actions/checkout@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and push Web App (kevsite)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deployment/build.Dockerfile
          push: true
          tags: kwjordanjr/kevhub:kevsite
 
      - name: Build and push Reverse Proxy
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deployment/nginx.Dockerfile
          push: true
          tags: kwjordanjr/kevhub:nginx

  update_ssh_linode:
    name: Telling Linode Server to Update
    needs: "push_to_registry"
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      with:
        envs: DOCKERHUB_USERNAME,DOCKERHUB_PASSWORD
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash update.sh